<?php

return [
    'api_key' => env('EVOLINK_API_KEY', ''),
    'base_url' => env('EVOLINK_BASE_URL', 'https://api.evolink.ai/v1'),
    'text_model' => env('EVOLINK_TEXT_MODEL', 'deepseek-v4-pro'),
    'voice_design_model' => env('EVOLINK_VOICE_DESIGN_MODEL', 'qwen-voice-design'),
    'voice_model' => env('EVOLINK_VOICE_MODEL', 'qwen3-tts-vd'),
    'tts_voice' => env('EVOLINK_TTS_VOICE', 'male_deep'),
    'local_tts_enabled' => (bool) env('LOCAL_TTS_ENABLED', true),
    'local_tts_voice' => env('LOCAL_TTS_VOICE', 'vi-VN-HoaiMyNeural'),
    'local_tts_rate' => env('LOCAL_TTS_RATE', '+8%'),
    'file_upload_base_url' => env('EVOLINK_FILE_UPLOAD_BASE_URL', 'https://files-api.evolink.ai'),
    'image_model' => env('EVOLINK_IMAGE_MODEL', 'gemini-3-pro-image-preview'),
    'image_quality' => env('EVOLINK_IMAGE_QUALITY', '1K'),
    'generate_product_images' => (bool) env('GENERATE_PRODUCT_IMAGES', true),
    'product_scene_count' => (int) env('PRODUCT_SCENE_COUNT', 2),
    'video_model' => env('EVOLINK_VIDEO_MODEL', 'kling-v3-text-to-video'),
    'video_aspect_ratio' => env('EVOLINK_VIDEO_ASPECT_RATIO', '9:16'),
    'video_quality' => env('EVOLINK_VIDEO_QUALITY', '1080p'),
    'video_sound' => env('EVOLINK_VIDEO_SOUND', 'off'),
    'monetization_duration' => (int) env('EVOLINK_MONETIZATION_VIDEO_DURATION', env('EVOLINK_VIDEO_DURATION', 15)),
    'affiliate_duration' => (int) env('EVOLINK_AFFILIATE_VIDEO_DURATION', env('EVOLINK_VIDEO_DURATION', 15)),
    'max_video_duration' => (int) env('EVOLINK_MAX_VIDEO_DURATION', 15),
    'poll_interval' => (int) env('EVOLINK_POLL_INTERVAL', 5),
    'video_timeout' => (int) env('EVOLINK_VIDEO_TIMEOUT', 900),
    'ffmpeg_path' => env('FFMPEG_PATH', 'ffmpeg'),
];
